// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/aerosystems/checkmail-service/internal/middleware"
	"github.com/aerosystems/checkmail-service/internal/presenters/rest"
	"github.com/aerosystems/checkmail-service/internal/repository/pg"
	"github.com/aerosystems/checkmail-service/internal/repository/rpc"
	"github.com/aerosystems/checkmail-service/internal/usecases"
	"github.com/aerosystems/checkmail-service/pkg/gorm_postgres"
	"github.com/aerosystems/checkmail-service/pkg/logger"
	"github.com/aerosystems/checkmail-service/pkg/oauth_service"
	"github.com/sirupsen/logrus"
	"gorm.io/gorm"
)

import (
	_ "github.com/aerosystems/checkmail-service/docs"
)

// Injectors from wire.go:

//go:generate wire
func InitializeApp() *App {
	logger := ProvideLogger()
	logrusLogger := ProvideLogrusLogger(logger)
	baseHandler := ProvideBaseHandler(logrusLogger)
	entry := ProvideLogrusEntry(logger)
	db := ProvideGormPostgres(entry)
	domainRepo := ProvideDomainRepo(db)
	rootDomainRepo := ProvideRootDomainRepo(db)
	domainUsecase := ProvideDomainUsecase(domainRepo, rootDomainRepo)
	domainHandler := ProvideDomainHandler(baseHandler, domainUsecase)
	filterRepo := ProvideFilterRepo(db)
	projectRepo := ProvideProjectRepo()
	filterUsecase := ProvideFilterUsecase(rootDomainRepo, filterRepo, projectRepo)
	filterHandler := ProvideFilterHandler(baseHandler, filterUsecase)
	inspectUsecase := ProvideInspectUsecase(logrusLogger, domainRepo, rootDomainRepo, filterRepo)
	inspectHandler := ProvideInspectHandler(baseHandler, inspectUsecase)
	reviewRepo := ProvideReviewRepo(db)
	reviewUsecase := ProvideReviewUsecase(reviewRepo, rootDomainRepo)
	reviewHandler := ProvideReviewHandler(baseHandler, reviewUsecase)
	accessTokenService := ProvideAccessTokenService()
	oAuthMiddleware := ProvideOAuthMiddleware(accessTokenService)
	basicAuthMiddleware := ProvideBasicAuthMiddleware()
	app := NewApp(domainHandler, filterHandler, inspectHandler, reviewHandler, oAuthMiddleware, basicAuthMiddleware)
	return app
}

func ProvideApp(domainHandler *rest.DomainHandler, filterHandler *rest.FilterHandler, inspectHandler *rest.InspectHandler, reviewHandler *rest.ReviewHandler, oauthMiddleware *middleware.OAuthMiddleware, basicAuthMiddleware *middleware.BasicAuthMiddleware) *App {
	app := NewApp(domainHandler, filterHandler, inspectHandler, reviewHandler, oauthMiddleware, basicAuthMiddleware)
	return app
}

func ProvideLogger() *logger.Logger {
	loggerLogger := logger.NewLogger()
	return loggerLogger
}

func ProvideGormPostgres(у *logrus.Entry) *gorm.DB {
	db := GormPostgres.NewClient(у)
	return db
}

func ProvideBaseHandler(log *logrus.Logger) *rest.BaseHandler {
	baseHandler := rest.NewBaseHandler(log)
	return baseHandler
}

func ProvideDomainHandler(baseHandler *rest.BaseHandler, domainUsecase rest.DomainUsecase) *rest.DomainHandler {
	domainHandler := rest.NewDomainHandler(baseHandler, domainUsecase)
	return domainHandler
}

func ProvideFilterHandler(baseHandler *rest.BaseHandler, filterUsecase rest.FilterUsecase) *rest.FilterHandler {
	filterHandler := rest.NewFilterHandler(baseHandler, filterUsecase)
	return filterHandler
}

func ProvideInspectHandler(baseHandler *rest.BaseHandler, inspectUsecase rest.InspectUsecase) *rest.InspectHandler {
	inspectHandler := rest.NewInspectHandler(baseHandler, inspectUsecase)
	return inspectHandler
}

func ProvideReviewHandler(baseHandler *rest.BaseHandler, reviewUsecase rest.ReviewUsecase) *rest.ReviewHandler {
	reviewHandler := rest.NewReviewHandler(baseHandler, reviewUsecase)
	return reviewHandler
}

func ProvideDomainUsecase(domainRepo usecases.DomainRepository, rootDomainRepo usecases.RootDomainRepository) *usecases.DomainUsecase {
	domainUsecase := usecases.NewDomainUsecase(domainRepo, rootDomainRepo)
	return domainUsecase
}

func ProvideFilterUsecase(rootDomainRepo usecases.RootDomainRepository, filterRepo usecases.FilterRepository, projectRepo usecases.ProjectRepository) *usecases.FilterUsecase {
	filterUsecase := usecases.NewFilterUsecase(rootDomainRepo, filterRepo, projectRepo)
	return filterUsecase
}

func ProvideInspectUsecase(log *logrus.Logger, domainRepo usecases.DomainRepository, rootDomainRepo usecases.RootDomainRepository, filterRepo usecases.FilterRepository) *usecases.InspectUsecase {
	inspectUsecase := usecases.NewInspectUsecase(log, domainRepo, rootDomainRepo, filterRepo)
	return inspectUsecase
}

func ProvideReviewUsecase(domainReviewRepo usecases.ReviewRepository, rootDomainRepo usecases.RootDomainRepository) *usecases.ReviewUsecase {
	reviewUsecase := usecases.NewReviewUsecase(domainReviewRepo, rootDomainRepo)
	return reviewUsecase
}

func ProvideDomainRepo(db *gorm.DB) *pg.DomainRepo {
	domainRepo := pg.NewDomainRepo(db)
	return domainRepo
}

func ProvideRootDomainRepo(db *gorm.DB) *pg.RootDomainRepo {
	rootDomainRepo := pg.NewRootDomainRepo(db)
	return rootDomainRepo
}

func ProvideFilterRepo(db *gorm.DB) *pg.FilterRepo {
	filterRepo := pg.NewFilterRepo(db)
	return filterRepo
}

func ProvideReviewRepo(db *gorm.DB) *pg.ReviewRepo {
	reviewRepo := pg.NewReviewRepo(db)
	return reviewRepo
}

func ProvideProjectRepo() *rpcRepo.ProjectRepo {
	projectRepo := rpcRepo.NewProjectRepo()
	return projectRepo
}

func ProvideAccessTokenService() *OAuthService.AccessTokenService {
	accessTokenService := OAuthService.NewAccessTokenService()
	return accessTokenService
}

func ProvideOAuthMiddleware(tokenService middleware.TokenService) *middleware.OAuthMiddleware {
	oAuthMiddleware := middleware.NewOAuthMiddleware(tokenService)
	return oAuthMiddleware
}

func ProvideBasicAuthMiddleware() *middleware.BasicAuthMiddleware {
	basicAuthMiddleware := middleware.NewBasicAuthMiddleware()
	return basicAuthMiddleware
}

// wire.go:

func ProvideLogrusEntry(log *logger.Logger) *logrus.Entry {
	return logrus.NewEntry(log.Logger)
}

func ProvideLogrusLogger(log *logger.Logger) *logrus.Logger {
	return log.Logger
}
